### ISSUE TITLE
Search bar in Library calls empty (old) onSearch method

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1026]
After entering a search term inside the Searchbar of the "Library" tab the wrong `onSearch` instance is used. To be more exact, `onSearch` is always `null`, because `setOnSearch(Consumer<String> onSearch)` can't be called before the constructor of the class and therefore before `this.searchBar = new SearchBox(onSearch, () -> {});`.

**Comment by plata** [comment]
I've just compared the search for library and apps. 
ApplicationSidebar
```Java
this.searchBar = new SearchBox(text -> this.onFilterTextEnter.accept(text), () -> this.onFilterClear.run());
```
LibrarySidebar
```Java
this.searchBar = new SearchBox(onSearch, () -> {});
```

The main problem is that the whole filtering is not implemented properly for library (it calls `updateLibrary` instead of using the `FilteredList`). We need the same behavior as `ViewApps#processFilterText`. I think that this should be implemented in the `SearchBox` directly because we want the same behavior in all tabs.

**Comment by madoar** [comment]
I'm not sure I understand your argument.
What exactly do you want to add to the `SearchBox` class?

**Comment by plata** [comment]
For example the `pause`.
